import OAI.AlgebraicGeometry.StableCoordinate.DeterminantRing
import OAI.AlgebraicGeometry.StableCoordinate.ObstructionDefinitions
import OAI.AlgebraicGeometry.StableCoordinate.HomogeneousQuotientWeight

namespace OAI

/-!
# Fiber weights on the actual determinant quotient

The Laurent coaction is induced by the exact weights `(1,1,-1,-1,0)` on
`a,d,b,c,u`.  We establish the final weight contradiction in the actual
quotient ring, not just in an abstract polynomial algebra: an element in
the image of `k[a,d,u]` with negative fiber weight is zero.
-/

namespace StableCoordinate
namespace DeterminantWeights

open MvPolynomial
open DeterminantRing
open scoped LaurentPolynomial

noncomputable section

variable (k : Type*) [CommRing k]

/-- The determinant relation is homogeneous of fiber weight zero. -/
theorem relation_fiber_homogeneous :
    (relation k).IsWeightedHomogeneous Obstruction.fiberWeight 0 := by
  have hac : (X 0 * X 3 : P k).IsWeightedHomogeneous Obstruction.fiberWeight 0 := by
    simpa [Obstruction.fiberWeight] using
      (isWeightedHomogeneous_X k Obstruction.fiberWeight (0 : Fin 5)).mul
        (isWeightedHomogeneous_X k Obstruction.fiberWeight (3 : Fin 5))
  have hbd : (X 2 * X 1 : P k).IsWeightedHomogeneous Obstruction.fiberWeight 0 := by
    simpa [Obstruction.fiberWeight] using
      (isWeightedHomogeneous_X k Obstruction.fiberWeight (2 : Fin 5)).mul
        (isWeightedHomogeneous_X k Obstruction.fiberWeight (1 : Fin 5))
  exact (weightedHomogeneousSubmodule k Obstruction.fiberWeight 0).sub_mem
    ((weightedHomogeneousSubmodule k Obstruction.fiberWeight 0).sub_mem hac hbd)
    (isWeightedHomogeneous_one k Obstruction.fiberWeight)

/-- The genuine fiber-weight coaction on `k[a,d,b,c,u]/(ac-bd-1)`. -/
def fiberCoaction : C k →ₐ[k] LaurentPolynomial (C k) :=
  HomogeneousQuotientWeight.coaction Obstruction.fiberWeight (relation k)
    (relation_fiber_homogeneous k)

@[simp]
theorem fiberCoaction_generator (i : Fin 5) :
    fiberCoaction k (generator k i) =
      AddMonoidAlgebra.single (Obstruction.fiberWeight i) (generator k i) :=
  HomogeneousQuotientWeight.coaction_variable _ _ _ i

@[simp] theorem fiberCoaction_a :
    fiberCoaction k (a k) = AddMonoidAlgebra.single 1 (a k) := by
  simp [a, Obstruction.fiberWeight]
@[simp] theorem fiberCoaction_d :
    fiberCoaction k (d k) = AddMonoidAlgebra.single 1 (d k) := by
  simp [d, Obstruction.fiberWeight]
@[simp] theorem fiberCoaction_b :
    fiberCoaction k (b k) = AddMonoidAlgebra.single (-1) (b k) := by
  simp [b, Obstruction.fiberWeight]
@[simp] theorem fiberCoaction_c :
    fiberCoaction k (c k) = AddMonoidAlgebra.single (-1) (c k) := by
  simp [c, Obstruction.fiberWeight]
@[simp] theorem fiberCoaction_u :
    fiberCoaction k (u k) = AddMonoidAlgebra.single 0 (u k) := by
  simp [u, Obstruction.fiberWeight]

/-- The first quadric coordinate `x=ab` is fixed by fiber scaling. -/
@[simp] theorem fiberCoaction_ab :
    fiberCoaction k (a k * b k) = AddMonoidAlgebra.single 0 (a k * b k) := by
  rw [map_mul, fiberCoaction_a, fiberCoaction_b, AddMonoidAlgebra.single_mul_single]
  norm_num

/-- The second quadric coordinate `y=dc` is fixed by fiber scaling. -/
@[simp] theorem fiberCoaction_dc :
    fiberCoaction k (d k * c k) = AddMonoidAlgebra.single 0 (d k * c k) := by
  rw [map_mul, fiberCoaction_d, fiberCoaction_c, AddMonoidAlgebra.single_mul_single]
  norm_num

/-- The third quadric coordinate `z=db` is fixed by fiber scaling. -/
@[simp] theorem fiberCoaction_db :
    fiberCoaction k (d k * b k) = AddMonoidAlgebra.single 0 (d k * b k) := by
  rw [map_mul, fiberCoaction_d, fiberCoaction_b, AddMonoidAlgebra.single_mul_single]
  norm_num

/-- Every polynomial in the four base quadric coordinates is fiber-invariant. -/
theorem fiberCoaction_of_mem_quadric_adjoin {q : C k}
    (hq : q ∈ Algebra.adjoin k (Set.range ![a k * b k, d k * c k, d k * b k, u k])) :
    fiberCoaction k q = AddMonoidAlgebra.single 0 q := by
  apply AlgHom.adjoin_le_equalizer (fiberCoaction k)
    (AddMonoidAlgebra.singleZeroAlgHom : C k →ₐ[k] LaurentPolynomial (C k)) _ hq
  rintro x ⟨i, rfl⟩
  fin_cases i
  · exact fiberCoaction_ab k
  · exact fiberCoaction_dc k
  · exact fiberCoaction_db k
  · exact fiberCoaction_u k

/-- Homogeneous images in the quotient satisfy the corresponding Laurent
weight identity. -/
theorem fiberCoaction_mk_of_homogeneous {p : P k} {n : ℤ}
    (hp : p.IsWeightedHomogeneous Obstruction.fiberWeight n) :
    fiberCoaction k (mk k p) = AddMonoidAlgebra.single n (mk k p) :=
  HomogeneousQuotientWeight.coaction_mk_of_homogeneous _ _ _ hp

/-- Membership in the polynomial subalgebra generated by `a,d,u` gives only
nonnegative fiber powers. -/
theorem fiberCoaction_mem_nonnegative_of_mem_baseRange {q : C k}
    (hq : q ∈ (baseMap (k := k)).range) :
    fiberCoaction k q ∈ LaurentWeightObstruction.nonnegativePart
      (k := k) (A := C k) := by
  have hq' : q ∈ Algebra.adjoin k (Set.range ![a k, d k, u k]) := by
    simpa only [baseMap, MvPolynomial.aeval_range] using hq
  apply LaurentWeightObstruction.adjoin_mem_nonnegativePart (fiberCoaction k) _ hq'
  rintro x ⟨i, rfl⟩
  fin_cases i
  · simpa [Obstruction.fiberWeight, a, d, u] using LaurentWeightObstruction.single_mem_nonnegativePart
      (k := k) (1 : ℤ) (by norm_num) (a k)
  · simpa [Obstruction.fiberWeight, a, d, u] using LaurentWeightObstruction.single_mem_nonnegativePart
      (k := k) (1 : ℤ) (by norm_num) (d k)
  · simpa [Obstruction.fiberWeight, a, d, u] using LaurentWeightObstruction.single_mem_nonnegativePart
      (k := k) (0 : ℤ) (by norm_num) (u k)

/-- The final rigidity obstruction in the actual determinant quotient,
stated directly using its fiber coaction. -/
theorem eq_zero_of_mem_baseRange_of_negative_weight {q : C k}
    (hq : q ∈ (baseMap (k := k)).range) {n : ℤ} (hn : n < 0)
    (hweight : fiberCoaction k q = AddMonoidAlgebra.single n q) : q = 0 := by
  apply LaurentWeightObstruction.eq_zero_of_single_mem_nonnegativePart (k := k) hn
  rw [← hweight]
  exact fiberCoaction_mem_nonnegative_of_mem_baseRange k hq

/-- The same obstruction for the image definition of a homogeneous quotient
piece.  This is the interface consumed by a quotient grading. -/
theorem eq_zero_of_mem_baseRange_of_homogeneous_representative {q : C k}
    (hq : q ∈ (baseMap (k := k)).range) {n : ℤ} (hn : n < 0)
    (hh : ∃ p : P k, p.IsWeightedHomogeneous Obstruction.fiberWeight n ∧ mk k p = q) :
    q = 0 := by
  obtain ⟨p, hp, rfl⟩ := hh
  exact eq_zero_of_mem_baseRange_of_negative_weight k hq hn
    (fiberCoaction_mk_of_homogeneous k hp)

/-- In particular, the nonzero coefficient of fiber weight `-2` required
by the source's final step cannot lie in `k[a,d,u]`. -/
theorem no_nonzero_baseRange_weight_neg_two {q : C k} (hq0 : q ≠ 0)
    (hq : q ∈ (baseMap (k := k)).range) :
    ¬ ∃ p : P k, p.IsWeightedHomogeneous Obstruction.fiberWeight (-2) ∧ mk k p = q := by
  intro hh
  exact hq0 (eq_zero_of_mem_baseRange_of_homogeneous_representative k hq (by norm_num) hh)

/-- Image-submodule form of the final obstruction; this matches the
standard grading on a quotient by a homogeneous relation. -/
theorem eq_zero_of_mem_baseRange_of_mem_homogeneous_piece {q : C k}
    (hq : q ∈ (baseMap (k := k)).range) {n : ℤ} (hn : n < 0)
    (hh : q ∈ (weightedHomogeneousSubmodule k Obstruction.fiberWeight n).map
      (mk k).toLinearMap) : q = 0 := by
  obtain ⟨p, hp, hpq⟩ := hh
  exact eq_zero_of_mem_baseRange_of_homogeneous_representative k hq hn ⟨p, hp, hpq⟩

/-- Both terms of the source coefficient `c*D(b)-b*D(c)` have fiber weight
`-2` whenever `D` preserves the fiber weights of `b` and `c`. -/
theorem coefficient_weight_neg_two {r s : C k}
    (hr : fiberCoaction k r = AddMonoidAlgebra.single (-1) r)
    (hs : fiberCoaction k s = AddMonoidAlgebra.single (-1) s) :
    fiberCoaction k (c k * r - b k * s) =
      AddMonoidAlgebra.single (-2) (c k * r - b k * s) := by
  rw [map_sub, map_mul, map_mul, fiberCoaction_c, fiberCoaction_b, hr, hs,
    AddMonoidAlgebra.single_mul_single, AddMonoidAlgebra.single_mul_single,
    ← AddMonoidAlgebra.single_sub]
  norm_num

/-- Final coefficient vanishing, ready to combine with the determinant
coefficient's nonvanishing for a nonzero derivation. -/
theorem coefficient_eq_zero_of_mem_baseRange {r s : C k}
    (hr : fiberCoaction k r = AddMonoidAlgebra.single (-1) r)
    (hs : fiberCoaction k s = AddMonoidAlgebra.single (-1) s)
    (hq : c k * r - b k * s ∈ (baseMap (k := k)).range) :
    c k * r - b k * s = 0 := by
  exact eq_zero_of_mem_baseRange_of_negative_weight k hq (by norm_num)
    (coefficient_weight_neg_two k hr hs)

end
end DeterminantWeights
end StableCoordinate

end OAI
