import OAI.AlgebraicGeometry.StableCoordinate.ReesCoefficientCriterion
import OAI.AlgebraicGeometry.StableCoordinate.WeightedInitialKernel

namespace OAI

/-!
# Kernel of the polynomial map to a principal weighted associated graded algebra

The proof connects three concrete calculations:
* coefficientwise vanishing in the Rees special fiber;
* the exact lower-representative criterion for a homogeneous polynomial;
* degreewise membership in a homogeneous principal ideal.

No associated-graded domain assumption or unproved initial-ideal identification
is used in this kernel computation.
-/

noncomputable section

namespace StableCoordinate.GradedPresentationKernel

open MvPolynomial WeightedInitial

variable {k σ A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- Membership in the actual image of the weighted filtration is precisely the
existence of a bounded polynomial representative. -/
theorem mem_boundedImage_iff (w : σ → ℤ)
    (φ : MvPolynomial σ k →ₐ[k] A) (p : MvPolynomial σ k) (d : ℤ) :
    φ p ∈ (boundedSubmodule w d).map φ.toLinearMap ↔
      ∃ r : MvPolynomial σ k, Bounded w r d ∧ φ r = φ p := Iff.rfl

/-- A homogeneous polynomial maps one filtration step lower exactly when it
belongs to the ideal generated by the top component of the defining relation. -/
theorem homogeneous_image_mem_lower_iff [IsDomain k]
    (w : σ → ℤ) (φ : MvPolynomial σ k →ₐ[k] A)
    (F : ℤ → Submodule k A)
    (hF : ∀ (p : MvPolynomial σ k) (d : ℤ),
      φ p ∈ F d ↔ ∃ r : MvPolynomial σ k, Bounded w r d ∧ φ r = φ p)
    (H : MvPolynomial σ k) (e : ℤ)
    (hH : Bounded w H e) (hHt : weightedHomogeneousComponent w e H ≠ 0)
    (hker : RingHom.ker φ.toRingHom = Ideal.span ({H} : Set (MvPolynomial σ k)))
    {p : MvPolynomial σ k} {d : ℤ} (hp : IsWeightedHomogeneous w p d) :
    φ p ∈ F (d - 1) ↔
      p ∈ Ideal.span ({weightedHomogeneousComponent w e H} : Set (MvPolynomial σ k)) := by
  rw [hF p (d - 1), ← homogeneous_quotient_kernel_iff w H e hH hHt hp]
  constructor
  · rintro ⟨r, hr, heq⟩
    refine ⟨r, hr, ?_⟩
    rw [← hker, RingHom.mem_ker]
    change φ (p - r) = 0
    rw [map_sub, heq, sub_self]
  · rintro ⟨r, hr, hpr⟩
    refine ⟨r, hr, ?_⟩
    rw [← hker, RingHom.mem_ker] at hpr
    change φ (p - r) = 0 at hpr
    rw [map_sub, sub_eq_zero] at hpr
    exact hpr.symm

/-- Top components generate a homogeneous principal ideal, including for
arbitrary integer weights. -/
theorem top_principal_mem_iff (w : σ → ℤ) (H p : MvPolynomial σ k) (e : ℤ) :
    p ∈ Ideal.span ({weightedHomogeneousComponent w e H} : Set (MvPolynomial σ k)) ↔
      ∀ d : ℤ, weightedHomogeneousComponent w d p ∈
        Ideal.span ({weightedHomogeneousComponent w e H} : Set (MvPolynomial σ k)) := by
  let := weightedGradedAlgebra k w
  apply mem_iff_weightedHomogeneousComponent_mem
  apply Ideal.homogeneous_span
  intro q hq
  have hq' : q = weightedHomogeneousComponent w e H := Set.mem_singleton_iff.mp hq
  subst q
  exact ⟨e, weightedHomogeneousComponent_isWeightedHomogeneous e H⟩

/-- Exact kernel theorem for a polynomial-to-Rees construction whose coefficients
are the images of weighted homogeneous components.  The `hF` and `hcoeff`
arguments are compatibility identities for the constructed maps, not
assumptions about the principal theorem. -/
theorem kernel_eq_top_principal [IsDomain k]
    (w : σ → ℤ) (φ : MvPolynomial σ k →ₐ[k] A)
    (F : ℤ → Submodule k A) [SetLike.GradedMonoid F] (hmono : Monotone F)
    (hF : ∀ (p : MvPolynomial σ k) (d : ℤ),
      φ p ∈ F d ↔ ∃ r : MvPolynomial σ k, Bounded w r d ∧ φ r = φ p)
    (H : MvPolynomial σ k) (e : ℤ)
    (hH : Bounded w H e) (hHt : weightedHomogeneousComponent w e H ≠ 0)
    (hker : RingHom.ker φ.toRingHom = Ideal.span ({H} : Set (MvPolynomial σ k)))
    (ψ : MvPolynomial σ k →ₐ[k] FilteredRees.rees F)
    (hcoeff : ∀ (p : MvPolynomial σ k) (d : ℤ),
      ((ψ p : FilteredRees.rees F) : LaurentPolynomial A).coeff d =
        φ (weightedHomogeneousComponent w d p)) :
    RingHom.ker ((Ideal.Quotient.mkₐ k (FilteredRees.parameterIdeal F hmono)).comp ψ).toRingHom =
      Ideal.span ({weightedHomogeneousComponent w e H} : Set (MvPolynomial σ k)) := by
  ext p
  change Ideal.Quotient.mk (FilteredRees.parameterIdeal F hmono) (ψ p) = 0 ↔ _
  rw [FilteredRees.quotient_mk_eq_zero_iff]
  simp_rw [hcoeff]
  calc
    (∀ d : ℤ, φ (weightedHomogeneousComponent w d p) ∈ F (d - 1)) ↔
        ∀ d : ℤ, weightedHomogeneousComponent w d p ∈
          Ideal.span ({weightedHomogeneousComponent w e H} : Set (MvPolynomial σ k)) := by
      apply forall_congr'
      intro d
      exact homogeneous_image_mem_lower_iff w φ F hF H e hH hHt hker
        (weightedHomogeneousComponent_isWeightedHomogeneous d p)
    _ ↔ p ∈ Ideal.span ({weightedHomogeneousComponent w e H} : Set (MvPolynomial σ k)) :=
      (top_principal_mem_iff w H p e).symm

end StableCoordinate.GradedPresentationKernel

end

end OAI
