import Mathlib.RingTheory.Ideal.Quotient.Operations

namespace OAI

/-!
# Successive hypersurface and fiber quotients

The source uses `A = P/(H)` and then `A/(p-lam)`.  This file identifies the
successive quotient, as an algebra, with `P/(H,p-lam)`.  It is purely a
quotient interface and contains no geometric or polynomial hypotheses.
-/

namespace StableCoordinate
namespace IteratedQuotient

variable (k A : Type*) [CommRing k] [CommRing A] [Algebra k A]

/-- The ideal generated by a single equation. -/
abbrev relationIdeal (a : A) : Ideal A := Ideal.span {a}

/-- The ideal generated by two simultaneous equations. -/
abbrev pairIdeal (a b : A) : Ideal A := Ideal.span {a, b}

lemma span_pair_eq_sup (a b : A) :
    pairIdeal A a b = relationIdeal A a ⊔ relationIdeal A b := by
  rw [pairIdeal, relationIdeal, relationIdeal, Ideal.span_insert]

lemma map_relationIdeal (a b : A) :
    (relationIdeal A b).map (Ideal.Quotient.mkₐ k (relationIdeal A a)) =
      Ideal.span {Ideal.Quotient.mk (relationIdeal A a) b} := by
  simp only [relationIdeal, Ideal.map_span, Set.image_singleton,
    Ideal.Quotient.mkₐ_eq_mk]

/-- Two successive principal quotients are the quotient by the pair of equations. -/
noncomputable def equiv (a b : A) :
    ((A ⧸ relationIdeal A a) ⧸
      Ideal.span {Ideal.Quotient.mk (relationIdeal A a) b}) ≃ₐ[k]
        A ⧸ pairIdeal A a b :=
  (Ideal.quotientEquivAlgOfEq k (map_relationIdeal k A a b).symm).trans
    ((DoubleQuot.quotQuotEquivQuotSupₐ k (relationIdeal A a)
      (relationIdeal A b)).trans
        (Ideal.quotientEquivAlgOfEq k (span_pair_eq_sup A a b).symm))

@[simp] theorem equiv_mk_mk (a b x : A) :
    equiv k A a b
      (Ideal.Quotient.mk _ (Ideal.Quotient.mk (relationIdeal A a) x)) =
        Ideal.Quotient.mk (pairIdeal A a b) x := by
  rfl

@[simp] theorem equiv_symm_mk (a b x : A) :
    (equiv k A a b).symm (Ideal.Quotient.mk (pairIdeal A a b) x) =
      Ideal.Quotient.mk _ (Ideal.Quotient.mk (relationIdeal A a) x) := by
  apply (equiv k A a b).injective
  simp

/-- Ring-theoretic fibers have the expected simultaneous-equation presentation,
with the scalar subtraction performed in the appropriate algebra at each stage. -/
noncomputable def fiberEquiv (H p : A) (lam : k) :
    ((A ⧸ relationIdeal A H) ⧸ Ideal.span {
      Ideal.Quotient.mk (relationIdeal A H) p -
        algebraMap k (A ⧸ relationIdeal A H) lam}) ≃ₐ[k]
      A ⧸ pairIdeal A H (p - algebraMap k A lam) :=
  (Ideal.quotientEquivAlgOfEq k (by
    congr 1)).trans
      (equiv k A H (p - algebraMap k A lam))

@[simp] theorem fiberEquiv_mk_mk (H p x : A) (lam : k) :
    fiberEquiv k A H p lam
      (Ideal.Quotient.mk _ (Ideal.Quotient.mk (relationIdeal A H) x)) =
        Ideal.Quotient.mk (pairIdeal A H (p - algebraMap k A lam)) x := by
  rfl

@[simp] theorem fiberEquiv_symm_mk (H p x : A) (lam : k) :
    (fiberEquiv k A H p lam).symm
      (Ideal.Quotient.mk (pairIdeal A H (p - algebraMap k A lam)) x) =
        Ideal.Quotient.mk _ (Ideal.Quotient.mk (relationIdeal A H) x) := by
  apply (fiberEquiv k A H p lam).injective
  simp

end IteratedQuotient
end StableCoordinate

end OAI
