import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.RingTheory.Adjoin.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous
import Mathlib.Tactic

namespace OAI

/-!
# Negative weights cannot occur in a nonnegatively generated subalgebra

We use Laurent polynomial coactions to express an integral weight.  The
argument applies directly inside an ambient algebra: no reflection of a
quotient grading and no injectivity of a chosen polynomial presentation is
required.  In the determinant algebra, the subalgebra generated by `a,d,u`
has only nonnegative fiber weights, whereas the last coefficient in the
source rigidity argument would have weight `-2`.
-/

namespace StableCoordinate
namespace LaurentWeightObstruction

open LaurentPolynomial
open scoped LaurentPolynomial

noncomputable section

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- Laurent polynomials with no negative powers, viewed as a `k`-subalgebra. -/
def nonnegativePart : Subalgebra k A[T;T⁻¹] :=
  (Polynomial.toLaurentAlg (R := A)).range.restrictScalars k

/-- A single nonnegative Laurent monomial is an ordinary polynomial. -/
theorem single_mem_nonnegativePart (n : ℤ) (hn : 0 ≤ n) (a : A) :
    AddMonoidAlgebra.single n a ∈ nonnegativePart (k := k) (A := A) := by
  lift n to ℕ using hn
  change ∃ p : Polynomial A, p.toLaurent = AddMonoidAlgebra.single (n : ℤ) a
  exact ⟨Polynomial.monomial n a, by
    simp [LaurentPolynomial.single_eq_C_mul_T, Polynomial.toLaurent_C_mul_T]⟩

/-- An ordinary polynomial cannot equal a nonzero Laurent monomial of
strictly negative degree. -/
theorem eq_zero_of_single_mem_nonnegativePart {n : ℤ} (hn : n < 0) {a : A}
    (h : AddMonoidAlgebra.single n a ∈ nonnegativePart (k := k) (A := A)) :
    a = 0 := by
  obtain ⟨p, hp⟩ := h
  change p.toLaurent = AddMonoidAlgebra.single n a at hp
  have hp0 : p = 0 := by
    calc
      p = LaurentPolynomial.trunc p.toLaurent := (Polynomial.trunc_toLaurent p).symm
      _ = LaurentPolynomial.trunc (AddMonoidAlgebra.single n a) := congrArg _ hp
      _ = 0 := by
        rw [LaurentPolynomial.single_eq_C_mul_T, LaurentPolynomial.trunc_C_mul_T]
        simp [not_le.mpr hn]
  have hs : AddMonoidAlgebra.single n a = (0 : A[T;T⁻¹]) := by
    rw [← hp, hp0, map_zero]
  have hc := congrArg (fun f : A[T;T⁻¹] => f.coeff n) hs
  simpa only [AddMonoidAlgebra.coeff_single, Finsupp.single_eq_same,
    AddMonoidAlgebra.coeff_zero, Finsupp.zero_apply] using hc

/-- If every element of a generating set has nonnegative weights under an
algebra homomorphism to Laurent polynomials, then its generated subalgebra
does too. -/
theorem adjoin_mem_nonnegativePart
    (ρ : A →ₐ[k] A[T;T⁻¹]) {s : Set A}
    (hs : ∀ a ∈ s, ρ a ∈ nonnegativePart (k := k) (A := A))
    {a : A} (ha : a ∈ Algebra.adjoin k s) :
    ρ a ∈ nonnegativePart (k := k) (A := A) := by
  have hle : Algebra.adjoin k s ≤ (nonnegativePart (k := k) (A := A)).comap ρ :=
    Algebra.adjoin_le hs
  exact hle ha

/-- The final weight obstruction in an arbitrary ambient algebra.  `ρ` may
be the weight coaction of a quotient algebra; no polynomial subalgebra
injectivity is needed. -/
theorem eq_zero_of_adjoin_of_negative_weight
    (ρ : A →ₐ[k] A[T;T⁻¹]) {s : Set A}
    (hs : ∀ a ∈ s, ρ a ∈ nonnegativePart (k := k) (A := A))
    {a : A} (ha : a ∈ Algebra.adjoin k s) {n : ℤ} (hn : n < 0)
    (hweight : ρ a = AddMonoidAlgebra.single n a) : a = 0 := by
  apply eq_zero_of_single_mem_nonnegativePart (k := k) hn
  rw [← hweight]
  exact adjoin_mem_nonnegativePart ρ hs ha

/-- Evaluation with each variable tagged by its integral weight. -/
def weightedEval {σ : Type*} (w : σ → ℤ) (f : σ → A) :
    MvPolynomial σ k →ₐ[k] A[T;T⁻¹] :=
  MvPolynomial.aeval fun i => AddMonoidAlgebra.single (w i) (f i)

/-- A homogeneous polynomial evaluates to one Laurent monomial under the
weighted evaluation homomorphism. -/
theorem weightedEval_of_homogeneous {σ : Type*} (w : σ → ℤ) (f : σ → A)
    {p : MvPolynomial σ k} {n : ℤ} (hp : p.IsWeightedHomogeneous w n) :
    weightedEval w f p = AddMonoidAlgebra.single n (MvPolynomial.aeval f p) := by
  induction hp using MvPolynomial.IsWeightedHomogeneous.induction_on with
  | zero => simp [weightedEval]
  | add p q hp hq ihp ihq =>
      simp only [map_add, ihp, ihq, AddMonoidAlgebra.single_add]
  | monomial d r hw =>
      simp only [weightedEval, MvPolynomial.aeval_monomial,
        AddMonoidAlgebra.single_pow, AddMonoidAlgebra.finsuppProd_single,
        LaurentPolynomial.algebraMap_apply, ← LaurentPolynomial.single_eq_C,
        AddMonoidAlgebra.single_mul_single, zero_add]
      rw [← Finsupp.weight_apply, hw]

/-- Coefficient extraction from weighted evaluation is evaluation of the
corresponding weighted homogeneous component. -/
theorem coeff_weightedEval {σ : Type*} (w : σ → ℤ) (f : σ → A)
    (p : MvPolynomial σ k) (n : ℤ) :
    (weightedEval w f p).coeff n =
      MvPolynomial.aeval f (MvPolynomial.weightedHomogeneousComponent w n p) := by
  classical
  induction p using MvPolynomial.induction_on' with
  | add p q hp hq =>
      simp only [map_add, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hp, hq]
  | monomial d r =>
      have hd : (MvPolynomial.monomial d r).IsWeightedHomogeneous w (Finsupp.weight w d) :=
        MvPolynomial.isWeightedHomogeneous_monomial w d r rfl
      rw [weightedEval_of_homogeneous w f hd]
      by_cases h : Finsupp.weight w d = n
      · subst n
        rw [MvPolynomial.IsWeightedHomogeneous.weightedHomogeneousComponent_same hd]
        simp only [AddMonoidAlgebra.coeff_single, Finsupp.single_eq_same]
      · rw [MvPolynomial.IsWeightedHomogeneous.weightedHomogeneousComponent_ne n hd (Ne.symm h)]
        simp only [map_zero, AddMonoidAlgebra.coeff_single, Finsupp.single_apply,
          ite_eq_right h]

end
end LaurentWeightObstruction
end StableCoordinate

end OAI
