import Mathlib

namespace OAI

/-!
# Homogeneous pieces of an affine modification

For an ideal `I` of `R`, this file identifies the Laurent subalgebra
`R[T, I/T]` with the Laurent polynomials whose coefficient at exponent
`n` belongs to `I ^ max (-n) 0`.  The grading in the source is opposite
to the Laurent exponent, so its positive degree-`ℓ` piece is
`T^(-ℓ) I^ℓ`.
-/

noncomputable section

namespace StableCoordinate.ModificationPieces

open LaurentPolynomial
open scoped LaurentPolynomial

variable {R : Type*} [CommRing R]

/-- The coefficient realization of the extended Rees algebra `R[T,I/T]`. -/
def extendedRees (I : Ideal R) : Subalgebra R R[T;T⁻¹] where
  carrier := { p | ∀ n : ℤ, p.coeff n ∈ I ^ (-n).toNat }
  zero_mem' n := by simp
  one_mem' n := by
    change (C (1 : R)).coeff n ∈ I ^ (-n).toNat
    rw [C_apply]
    split_ifs with hn
    · subst n
      simp
    · exact Ideal.zero_mem _
  add_mem' hp hq n := by
    simpa only [AddMonoidAlgebra.coeff_add, Finsupp.add_apply] using
      (I ^ (-n).toNat).add_mem (hp n) (hq n)
  mul_mem' hp hq n := by
    rw [AddMonoidAlgebra.coeff_mul]
    unfold Finsupp.sum
    apply Ideal.sum_mem
    intro a ha
    apply Ideal.sum_mem
    intro b hb
    dsimp only
    by_cases hab : a + b = n
    · rw [ite_eq_left hab]
      have hprod := Ideal.mul_mem_mul (hp a) (hq b)
      rw [← pow_add] at hprod
      exact Ideal.pow_le_pow_right (by omega) hprod
    · rw [ite_eq_right hab]
      exact Ideal.zero_mem _
  algebraMap_mem' r n := by
    change (C r).coeff n ∈ I ^ (-n).toNat
    rw [C_apply]
    split_ifs with hn
    · subst n
      simp
    · exact Ideal.zero_mem _

@[simp]
theorem mem_extendedRees_iff (I : Ideal R) (p : R[T;T⁻¹]) :
    p ∈ extendedRees I ↔ ∀ n : ℤ, p.coeff n ∈ I ^ (-n).toNat :=
  Iff.rfl

theorem single_mem_extendedRees_iff (I : Ideal R) (n : ℤ) (r : R) :
    AddMonoidAlgebra.single n r ∈ extendedRees I ↔ r ∈ I ^ (-n).toNat := by
  constructor
  · intro h
    simpa only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply, ite_true] using h n
  · intro h i
    by_cases hi : n = i
    · subst i
      simpa only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply, ite_true] using h
    · simp only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply, ite_eq_right hi]
      exact Ideal.zero_mem _

/-- The Laurent subalgebra generated by `T` and `r/T` for `r ∈ I`. -/
def modification (I : Ideal R) : Subalgebra R R[T;T⁻¹] :=
  Algebra.adjoin R
    (insert (T 1) ((fun r : R => C r * T (-1)) '' (I : Set R)))

theorem T_one_mem_modification (I : Ideal R) :
    (T 1 : R[T;T⁻¹]) ∈ modification I :=
  Algebra.subset_adjoin (Set.mem_insert _ _)

theorem numerator_mem_modification {I : Ideal R} {r : R} (hr : r ∈ I) :
    C r * T (-1) ∈ modification I :=
  Algebra.subset_adjoin (Set.mem_insert_of_mem _ ⟨r, hr, rfl⟩)

theorem modification_le_extendedRees (I : Ideal R) :
    modification I ≤ extendedRees I := by
  apply Algebra.adjoin_le
  rintro p (rfl | ⟨r, hr, rfl⟩)
  · change AddMonoidAlgebra.single 1 1 ∈ extendedRees I
    rw [single_mem_extendedRees_iff]
    simp
  · dsimp only
    rw [← single_eq_C_mul_T]
    change AddMonoidAlgebra.single (-1) r ∈ extendedRees I
    rw [single_mem_extendedRees_iff]
    simpa using hr

theorem negative_single_mem_modification {I : Ideal R} {n : ℕ} {r : R}
    (hr : r ∈ I ^ n) :
    AddMonoidAlgebra.single (-(n : ℤ)) r ∈ modification I := by
  induction n generalizing r with
  | zero =>
      change C r ∈ modification I
      exact (modification I).algebraMap_mem r
  | succ n ih =>
      rw [pow_succ'] at hr
      refine Submodule.smul_induction_on hr ?_ ?_
      · intro a ha b hb
        have h₁ := numerator_mem_modification ha
        have h₂ := ih hb
        rw [← single_eq_C_mul_T] at h₁
        convert (modification I).mul_mem h₁ h₂ using 1
        simp only [smul_eq_mul, AddMonoidAlgebra.single_mul_single, Nat.cast_add,
          Nat.cast_one, neg_add_rev]
      · intro a b ha hb
        simpa only [AddMonoidAlgebra.single_add] using
          (modification I).add_mem ha hb

theorem nonnegative_single_mem_modification (I : Ideal R) (n : ℤ) (hn : 0 ≤ n)
    (r : R) :
    AddMonoidAlgebra.single n r ∈ modification I := by
  have hT := (modification I).pow_mem (T_one_mem_modification I) n.toNat
  rw [T_pow, mul_one, Int.toNat_of_nonneg hn] at hT
  rw [single_eq_C_mul_T]
  exact (modification I).mul_mem ((modification I).algebraMap_mem r) hT

theorem single_mem_modification_of_mem_power {I : Ideal R} (n : ℤ) {r : R}
    (hr : r ∈ I ^ (-n).toNat) :
    AddMonoidAlgebra.single n r ∈ modification I := by
  by_cases hn : 0 ≤ n
  · exact nonnegative_single_mem_modification I n hn r
  · convert negative_single_mem_modification hr using 1
    congr 1
    omega

/-- The generator and coefficient definitions of the extended Rees algebra coincide. -/
theorem modification_eq_extendedRees (I : Ideal R) :
    modification I = extendedRees I := by
  apply le_antisymm (modification_le_extendedRees I)
  intro p hp
  rw [← p.sum_coeff_single]
  unfold Finsupp.sum
  apply Subalgebra.sum_mem
  intro n hn
  exact single_mem_modification_of_mem_power n (hp n)

/-- Exact Laurent monomial membership. -/
theorem single_mem_modification_iff (I : Ideal R) (n : ℤ) (r : R) :
    AddMonoidAlgebra.single n r ∈ modification I ↔ r ∈ I ^ (-n).toNat := by
  rw [modification_eq_extendedRees, single_mem_extendedRees_iff]

/-- The source's degree-`ℓ` piece, using `deg T = -1`. -/
theorem positive_piece (I : Ideal R) (ℓ : ℕ) (r : R) :
    C r * T (-(ℓ : ℤ)) ∈ modification I ↔ r ∈ I ^ ℓ := by
  rw [← single_eq_C_mul_T, single_mem_modification_iff]
  simp

/-- Every negative-exponent coefficient of a modification element lies in the
corresponding power of the center ideal. -/
theorem coefficient_mem_power {I : Ideal R} {p : R[T;T⁻¹]}
    (hp : p ∈ modification I) (ℓ : ℕ) :
    p.coeff (-(ℓ : ℤ)) ∈ I ^ ℓ := by
  have h := modification_le_extendedRees I hp (-(ℓ : ℤ))
  simpa using h

/-- Numerators whose division by `T` lies in a specified Laurent subalgebra. -/
def numeratorIdeal (S : Subalgebra R R[T;T⁻¹]) : Ideal R where
  carrier := { r | C r * T (-1) ∈ S }
  zero_mem' := by simp
  add_mem' hr hs := by
    change C (_ + _) * T (-1) ∈ S
    simpa only [map_add, add_mul] using S.add_mem hr hs
  smul_mem' a r hr := by
    change C (a * r) * T (-1) ∈ S
    rw [map_mul, mul_assoc]
    exact S.mul_mem (S.algebraMap_mem a) hr

/-- A presentation by an arbitrary chosen set of generators of the center. -/
def generatedModification (s : Set R) : Subalgebra R R[T;T⁻¹] :=
  Algebra.adjoin R (insert (T 1) ((fun r : R => C r * T (-1)) '' s))

/-- Passing from ideal generators to every numerator in the ideal does not change
the generated Laurent subalgebra. -/
theorem modification_span_eq (s : Set R) :
    modification (Ideal.span s) = generatedModification s := by
  apply le_antisymm
  · have hspan : Ideal.span s ≤ numeratorIdeal (generatedModification s) := by
      apply Ideal.span_le.mpr
      intro r hr
      exact Algebra.subset_adjoin (Set.mem_insert_of_mem _ ⟨r, hr, rfl⟩)
    apply Algebra.adjoin_le
    rintro p (rfl | ⟨r, hr, rfl⟩)
    · exact Algebra.subset_adjoin (Set.mem_insert _ _)
    · exact hspan hr
  · apply Algebra.adjoin_le
    rintro p (rfl | ⟨r, hr, rfl⟩)
    · exact T_one_mem_modification _
    · exact numerator_mem_modification (Ideal.subset_span hr)

/-- The exact two-generator presentation used for the distinguished ideal
`I=(f₀,g₀)`. -/
theorem modification_pair_eq (f g : R) :
    modification (Ideal.span ({f, g} : Set R)) =
      Algebra.adjoin R ({T 1, C f * T (-1), C g * T (-1)} : Set R[T;T⁻¹]) := by
  simpa only [generatedModification, Set.image_insert_eq, Set.image_singleton] using
    modification_span_eq ({f, g} : Set R)

/-- Laurent homogeneity for the source convention `deg T = -1`. -/
def Homogeneous (ℓ : ℤ) (p : R[T;T⁻¹]) : Prop :=
  ∀ n : ℤ, n ≠ -ℓ → p.coeff n = 0

theorem eq_single_of_homogeneous {ℓ : ℤ} {p : R[T;T⁻¹]}
    (hp : Homogeneous ℓ p) :
    p = AddMonoidAlgebra.single (-ℓ) (p.coeff (-ℓ)) := by
  apply LaurentPolynomial.ext
  intro n
  by_cases hn : n = -ℓ
  · subst n
    simp only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply, ite_true]
  · rw [hp n hn]
    simp only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply,
      ite_eq_right (Ne.symm hn)]

theorem homogeneous_single (ℓ : ℤ) (r : R) :
    Homogeneous ℓ (AddMonoidAlgebra.single (-ℓ) r) := by
  intro n hn
  simp only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply, ite_eq_right (Ne.symm hn)]

theorem homogeneous_zero (ℓ : ℤ) : Homogeneous ℓ (0 : R[T;T⁻¹]) := by
  intro n hn
  simp

theorem homogeneous_C (r : R) : Homogeneous 0 (C r) := by
  simpa only [neg_zero, LaurentPolynomial.single_eq_C] using homogeneous_single 0 r

namespace Homogeneous

theorem add {d : ℤ} {p q : R[T;T⁻¹]} (hp : Homogeneous d p) (hq : Homogeneous d q) :
    Homogeneous d (p + q) := by
  intro n hn
  simp only [AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hp n hn, hq n hn, add_zero]

theorem mul {d e : ℤ} {p q : R[T;T⁻¹]} (hp : Homogeneous d p) (hq : Homogeneous e q) :
    Homogeneous (d + e) (p * q) := by
  rw [eq_single_of_homogeneous hp, eq_single_of_homogeneous hq,
    AddMonoidAlgebra.single_mul_single, ← neg_add]
  exact homogeneous_single _ _

theorem pow {d : ℤ} {p : R[T;T⁻¹]} (hp : Homogeneous d p) (n : ℕ) :
    Homogeneous (n • d) (p ^ n) := by
  induction n with
  | zero =>
      simpa only [pow_zero, zero_nsmul, map_one] using homogeneous_C (1 : R)
  | succ n ih =>
      simpa only [pow_succ, succ_nsmul] using ih.mul hp

theorem sum {ι : Type*} (s : Finset ι) (p : ι → R[T;T⁻¹]) (d : ℤ)
    (hp : ∀ i ∈ s, Homogeneous d (p i)) : Homogeneous d (∑ i ∈ s, p i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using homogeneous_zero d
  | @insert i s his ih =>
      rw [Finset.sum_insert his]
      exact (hp i (Finset.mem_insert_self _ _)).add
        (ih (fun j hj => hp j (Finset.mem_insert_of_mem hj)))

theorem prod {ι : Type*} (s : Finset ι) (p : ι → R[T;T⁻¹]) (d : ι → ℤ)
    (hp : ∀ i ∈ s, Homogeneous (d i) (p i)) :
    Homogeneous (∑ i ∈ s, d i) (∏ i ∈ s, p i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa only [Finset.sum_empty, Finset.prod_empty, map_one] using homogeneous_C (1 : R)
  | @insert i s his ih =>
      rw [Finset.sum_insert his, Finset.prod_insert his]
      exact (hp i (Finset.mem_insert_self _ _)).mul
        (ih (fun j hj => hp j (Finset.mem_insert_of_mem hj)))

end Homogeneous

/-- Weighted polynomial evaluation preserves the source-to-Laurent grading
whenever the images of the independent variables have the specified weights. -/
theorem homogeneous_aeval {k σ : Type*} [CommRing k] [Algebra k R]
    (w : σ → ℤ) (v : σ → R[T;T⁻¹]) (hv : ∀ i, Homogeneous (w i) (v i))
    {p : MvPolynomial σ k} {d : ℤ} (hp : p.IsWeightedHomogeneous w d) :
    Homogeneous d (MvPolynomial.aeval v p) := by
  classical
  rw [p.as_sum, map_sum]
  apply Homogeneous.sum
  intro m hm
  rw [MvPolynomial.aeval_monomial]
  have hprod : Homogeneous (Finsupp.weight w m) (m.prod fun i n => v i ^ n) := by
    simpa only [Finsupp.weight_apply, Finsupp.sum, Finsupp.prod] using
      Homogeneous.prod m.support (fun i => v i ^ m i) (fun i => m i • w i)
        (fun i hi => (hv i).pow (m i))
  have hweight : Finsupp.weight w m = d := hp (MvPolynomial.mem_support_iff.mp hm)
  simpa only [LaurentPolynomial.algebraMap_apply, zero_add, hweight] using
    (homogeneous_C (algebraMap k R (p.coeff m))).mul hprod

/-- Every homogeneous positive-degree element has a numerator from the exact
power of the center ideal. -/
theorem homogeneous_numerator {I : Ideal R} {ℓ : ℕ} {p : R[T;T⁻¹]}
    (hp : p ∈ modification I) (hh : Homogeneous (ℓ : ℤ) p) :
    ∃ r ∈ I ^ ℓ, p = C r * T (-(ℓ : ℤ)) :=
  ⟨p.coeff (-(ℓ : ℤ)), coefficient_mem_power hp ℓ,
    (eq_single_of_homogeneous hh).trans (single_eq_C_mul_T _ _)⟩

/-- The nonzero-numerator form consumed by the coordinate obstruction. -/
theorem homogeneous_nonzero_numerator {I : Ideal R} {ℓ : ℕ} {p : R[T;T⁻¹]}
    (hp : p ∈ modification I) (hh : Homogeneous (ℓ : ℤ) p) (hne : p ≠ 0) :
    ∃ r ∈ I ^ ℓ, r ≠ 0 ∧ p = C r * T (-(ℓ : ℤ)) := by
  obtain ⟨r, hr, heq⟩ := homogeneous_numerator hp hh
  refine ⟨r, hr, ?_, heq⟩
  intro hzero
  apply hne
  simp [heq, hzero]

/-- In strictly positive degree the numerator lies in the center ideal itself. -/
theorem positive_nonzero_numerator {I : Ideal R} {ℓ : ℕ} {p : R[T;T⁻¹]}
    (hℓ : 0 < ℓ) (hp : p ∈ modification I)
    (hh : Homogeneous (ℓ : ℤ) p) (hne : p ≠ 0) :
    ∃ r ∈ I, r ≠ 0 ∧ p = C r * T (-(ℓ : ℤ)) := by
  obtain ⟨r, hr, hne, heq⟩ := homogeneous_nonzero_numerator hp hh hne
  exact ⟨r, Ideal.pow_le_self (Nat.ne_zero_of_lt hℓ) hr, hne, heq⟩

end StableCoordinate.ModificationPieces

end

end OAI
