import Mathlib.Algebra.MvPolynomial.Nilpotent
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Ideal.Span

namespace OAI

/-!
# Principal hypersurface ideals over a field

The elementary algebraic interface used in the proof of `cor:fibers` is that two
polynomials which generate the same ideal differ by a nonzero scalar.  This
module proves that statement and its transported form under algebra maps.
-/

namespace StableCoordinate

open MvPolynomial

variable {k σ : Type*} [Field k]

/-- Equal principal ideals in a polynomial ring over a field have generators
that differ by a nonzero scalar.  This includes the zero ideal. -/
theorem eq_nonzero_scalar_mul_of_span_singleton_eq
    {f g : MvPolynomial σ k}
    (h : Ideal.span ({f} : Set (MvPolynomial σ k)) = Ideal.span {g}) :
    ∃ c : k, c ≠ 0 ∧ f = C c * g := by
  obtain ⟨u, hu⟩ := (Ideal.span_singleton_eq_span_singleton.mp h).symm
  obtain ⟨c, hc, hcu⟩ :=
    MvPolynomial.isUnit_iff_eq_C_of_isReduced.mp u.isUnit
  exact ⟨c, isUnit_iff_ne_zero.mp hc, by simpa [hcu, mul_comm] using hu.symm⟩

/-- Scalar multiples by a nonzero field element generate the same ideal. -/
theorem span_singleton_eq_of_eq_nonzero_scalar_mul
    {f g : MvPolynomial σ k} {c : k} (hc : c ≠ 0) (h : f = C c * g) :
    Ideal.span ({f} : Set (MvPolynomial σ k)) = Ideal.span {g} := by
  rw [h]
  exact Ideal.span_singleton_mul_left_unit ((isUnit_iff_ne_zero.mpr hc).map C) g

/-- A precise algebraic form of the generator normalization step. -/
theorem span_singleton_eq_iff_nonzero_scalar_mul
    {f g : MvPolynomial σ k} :
    Ideal.span ({f} : Set (MvPolynomial σ k)) = Ideal.span {g} ↔
      ∃ c : k, c ≠ 0 ∧ f = C c * g := by
  constructor
  · exact eq_nonzero_scalar_mul_of_span_singleton_eq
  · rintro ⟨c, hc, h⟩
    exact span_singleton_eq_of_eq_nonzero_scalar_mul hc h

/-- Images of principal ideals under algebra maps are generated by the image
of the generator.  No surjectivity assumption is needed. -/
theorem map_span_singleton_algHom
    {A B : Type*} [CommRing A] [CommRing B] [Algebra k A] [Algebra k B]
    (φ : A →ₐ[k] B) (f : A) :
    Ideal.map φ.toRingHom (Ideal.span ({f} : Set A)) = Ideal.span {φ f} := by
  rw [Ideal.map_span, Set.image_singleton]
  rfl

/-- If an algebra map takes a polynomial principal ideal to another principal
ideal, its value on the generator is a nonzero scalar multiple of the target. -/
theorem eq_nonzero_scalar_mul_of_map_span_singleton_eq
    {τ : Type*} (φ : MvPolynomial σ k →ₐ[k] MvPolynomial τ k)
    {f : MvPolynomial σ k} {g : MvPolynomial τ k}
    (h : Ideal.map φ.toRingHom (Ideal.span ({f} : Set (MvPolynomial σ k))) =
      Ideal.span {g}) :
    ∃ c : k, c ≠ 0 ∧ φ f = C c * g := by
  apply eq_nonzero_scalar_mul_of_span_singleton_eq
  simpa only [map_span_singleton_algHom] using h

end StableCoordinate

end OAI
