import Mathlib.RingTheory.Derivation.Basic
import Mathlib.Tactic.Ring

namespace OAI

/-!
# Coefficients of derivations on the determinant-one hypersurface

This file formalizes the coefficient step of §5, equation `rig:q`, from the
supplied manuscript.  No local nilpotence or domain hypothesis is needed for
this purely algebraic step.  The nonzero criterion uses the stated generation
hypothesis rather than silently assuming the five displayed elements generate.
-/

namespace StableCoordinate

section DeterminantIdentities

variable {A : Type*} [CommRing A]

/-- The first coefficient identity follows from the determinant-one relation. -/
theorem determinant_coefficient_left (a d b c B C : A)
    (hdet : a * c - b * d = 1) (hcompat : a * C = d * B) :
    B = a * (c * B - b * C) := by
  symm
  calc
    a * (c * B - b * C) = (a * c - b * d) * B + b * (d * B - a * C) := by ring
    _ = B := by rw [hdet, hcompat]; ring

/-- The second coefficient identity follows from the same relation. -/
theorem determinant_coefficient_right (a d b c B C : A)
    (hdet : a * c - b * d = 1) (hcompat : a * C = d * B) :
    C = d * (c * B - b * C) := by
  symm
  calc
    d * (c * B - b * C) = (a * c - b * d) * C + c * (d * B - a * C) := by ring
    _ = C := by rw [hdet, hcompat]; ring

/-- The coefficient is unique, without cancellation or nonzero hypotheses. -/
theorem determinant_coefficient_unique (a d b c B C q : A)
    (hdet : a * c - b * d = 1) (hB : B = a * q) (hC : C = d * q) :
    q = c * B - b * C := by
  rw [hB, hC]
  calc
    q = (a * c - b * d) * q := by rw [hdet, one_mul]
    _ = c * (a * q) - b * (d * q) := by ring

end DeterminantIdentities

section Derivations

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- Differentiating `ac - bd = 1`, when `a,d` are invariant. -/
theorem derivation_determinant_compatibility (D : Derivation k A A)
    (a d b c : A) (hdet : a * c - b * d = 1)
    (ha : D a = 0) (hd : D d = 0) :
    a * D c = d * D b := by
  have h := congrArg D hdet
  simpa only [map_sub, Derivation.leibniz, ha, hd, smul_eq_mul,
    mul_zero, add_zero, zero_add, Derivation.map_one_eq_zero, sub_eq_zero] using h

/-- The source coefficient `q = c D(b) - b D(c)`. -/
def rigidityCoefficient (D : Derivation k A A) (b c : A) : A :=
  c * D b - b * D c

/-- The two identities in source equation `rig:q` in arbitrary commutative algebras. -/
theorem derivation_rigidityCoefficient (D : Derivation k A A)
    (a d b c : A) (hdet : a * c - b * d = 1)
    (ha : D a = 0) (hd : D d = 0) :
    D b = a * rigidityCoefficient D b c ∧ D c = d * rigidityCoefficient D b c := by
  have hcompat := derivation_determinant_compatibility D a d b c hdet ha hd
  exact ⟨determinant_coefficient_left a d b c (D b) (D c) hdet hcompat,
    determinant_coefficient_right a d b c (D b) (D c) hdet hcompat⟩

/-- A derivation of the algebra generated by `a,d,b,c,u` vanishes once these
five generators are invariant. -/
theorem derivation_eq_zero_of_five_generators (D : Derivation k A A)
    (a d b c u : A) (hgen : Algebra.adjoin k {a, d, b, c, u} = ⊤)
    (ha : D a = 0) (hd : D d = 0) (hb : D b = 0) (hc : D c = 0)
    (hu : D u = 0) : D = 0 := by
  apply Derivation.ext_of_adjoin_eq_top {a, d, b, c, u} hgen
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl | rfl | rfl | rfl <;>
    simp only [ha, hd, hb, hc, hu, Derivation.zero_apply]

/-- Under the exact generation condition used in §5, the source coefficient
is nonzero whenever the derivation is nonzero. -/
theorem rigidityCoefficient_ne_zero (D : Derivation k A A)
    (a d b c u : A) (hdet : a * c - b * d = 1)
    (hgen : Algebra.adjoin k {a, d, b, c, u} = ⊤)
    (ha : D a = 0) (hd : D d = 0) (hu : D u = 0) (hD : D ≠ 0) :
    rigidityCoefficient D b c ≠ 0 := by
  intro hq
  obtain ⟨hb, hc⟩ := derivation_rigidityCoefficient D a d b c hdet ha hd
  rw [hq, mul_zero] at hb hc
  exact hD (derivation_eq_zero_of_five_generators D a d b c u hgen ha hd hb hc hu)

end Derivations

end StableCoordinate

end OAI
