import OAI.AlgebraicGeometry.StableCoordinate.WeightedInitialKernel
import Mathlib.RingTheory.Ideal.Span

namespace OAI

/-!
# Principal initial ideals for integer-weighted polynomial rings

This module uses the canonical weighted-product API to prove that the ideal of
leading relations of a principal polynomial ideal is generated by the leading
form of its generator.  The weights are arbitrary integers.
-/

namespace StableCoordinate.WeightedInitial

noncomputable section

open MvPolynomial

variable {σ R : Type*} [CommRing R]
variable {w : σ → ℤ} {p q : MvPolynomial σ R} {d e : ℤ}

/-- `d` is the largest weight of a nonzero polynomial, including negative weights. -/
def IsTopDegree (w : σ → ℤ) (p : MvPolynomial σ R) (d : ℤ) : Prop :=
  Bounded w p d ∧ weightedHomogeneousComponent w d p ≠ 0

lemma homogeneous_bounded (hp : p.IsWeightedHomogeneous w d) : Bounded w p d :=
  fun _ hm => le_of_eq (hp hm)

lemma IsTopDegree.ne_zero (hp : IsTopDegree w p d) : p ≠ 0 := by
  intro h
  exact hp.2 (by rw [h, map_zero])

lemma IsTopDegree.of_homogeneous (hp : p.IsWeightedHomogeneous w d) (hne : p ≠ 0) :
    IsTopDegree w p d := by
  refine ⟨homogeneous_bounded hp, ?_⟩
  rwa [hp.weightedHomogeneousComponent_same]

lemma IsTopDegree.unique (hp : IsTopDegree w p d) (hq : IsTopDegree w p e) : d = e := by
  apply le_antisymm
  · by_contra h
    exact hp.2 (component_eq_zero_of_bounded hq.1 (lt_of_not_ge h))
  · by_contra h
    exact hq.2 (component_eq_zero_of_bounded hp.1 (lt_of_not_ge h))

/-- Projection through multiplication by a homogeneous polynomial.  This needs
no bound on the other factor and allows negative degree shifts. -/
lemma component_mul_homogeneous_left (hp : p.IsWeightedHomogeneous w d) (q : MvPolynomial σ R)
    (e : ℤ) :
    weightedHomogeneousComponent w (d + e) (p * q) =
      p * weightedHomogeneousComponent w e q := by
  classical
  ext m
  rw [coeff_weightedHomogeneousComponent, coeff_mul, coeff_mul, Finset.ite_sum_zero]
  apply Finset.sum_congr rfl
  rintro ⟨a, b⟩ hab
  rw [coeff_weightedHomogeneousComponent]
  by_cases ha : p.coeff a = 0
  · simp [ha]
  have hwa : Finsupp.weight w a = d := hp ha
  have hab' : a + b = m := Finset.mem_antidiagonal.mp hab
  have hwm : Finsupp.weight w m = d + Finsupp.weight w b := by
    rw [← hab', map_add, hwa]
  simp only [hwm, add_right_inj]
  split_ifs <;> simp_all

variable [NoZeroDivisors R]

/-- The initial ideal contains leading forms at the actual largest weights,
not all homogeneous components of the relation ideal. -/
def initialIdeal (w : σ → ℤ) (I : Ideal (MvPolynomial σ R)) : Ideal (MvPolynomial σ R) :=
  Ideal.span {f | ∃ p ∈ I, ∃ d : ℤ, IsTopDegree w p d ∧
    f = weightedHomogeneousComponent w d p}

/-- A principal relation has a principal weighted initial ideal. -/
theorem initialIdeal_span_singleton (hH : IsTopDegree w q e) :
    initialIdeal w (Ideal.span ({q} : Set (MvPolynomial σ R))) =
      Ideal.span ({weightedHomogeneousComponent w e q} : Set (MvPolynomial σ R)) := by
  apply le_antisymm
  · apply Ideal.span_le.mpr
    intro f hf
    obtain ⟨r, hr, d, hd, rfl⟩ := hf
    obtain ⟨t, ht⟩ := Ideal.mem_span_singleton.mp hr
    have htne : t ≠ 0 := by
      intro hzero
      exact hd.ne_zero (by rw [ht, hzero, mul_zero])
    obtain ⟨c, hc, hct⟩ := exists_top (w := w) htne
    have hp : IsTopDegree w (q * t) (e + c) := top_mul hH.1 hc hH.2 hct
    rw [← ht] at hp
    have hdegree := hd.unique hp
    rw [hdegree, ht, component_mul_of_bounded hH.1 hc]
    exact Ideal.mem_span_singleton.mpr ⟨weightedHomogeneousComponent w c t, rfl⟩
  · apply Ideal.span_le.mpr
    intro f hf
    have hf' : f = weightedHomogeneousComponent w e q := Set.mem_singleton_iff.mp hf
    subst f
    exact Ideal.subset_span ⟨q, Ideal.subset_span (Set.mem_singleton q), e, hH, rfl⟩


end
end StableCoordinate.WeightedInitial

end OAI
